### ISSUE TITLE
Tank

### ISSUE THREAD

**Issue by jkelly31415** [gswcm/CSCI4310_FA15_TP#1]
## TODO:
- [X] Template up (but incomplete).
- [X] simple AI using each action at least once.
- [ ] event handling:
  - [ ] tank collision (between tanks, walls, bullets...)
  - [ ] bullet collision (between tanks, walls, bullets...)

###  INFORMATION GIVEN TO OTHER CLASSES
public getters include:
int x
int y
double getBodyRot
double getGunRot
String getName

#### INTEGRATION
Q: What does the ENGINE need to handle and what does the TANK need to handle?

**Comment by inglemr** [comment]
Engine - Tank submits move that it wants to make and it is stored in a stack maintained by the engine
               The engine will tell the tank to move once the requested move is taken off the stack

Tank - Pushes action request to the engine to be placed on the stack all actions must be worth 1 turn    worth of action to be placed on the stack if a tank wishes to push more than one action it will have to add multiple actions to the stack


What are items need to be addressed or do you guys have a better idea for the handling of move/turns between the tank and engine
